# Generated by Django 5.1.4 on 2025-09-26 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='hero_video',
            field=models.FileField(blank=True, help_text='Upload hero video file', null=True, upload_to='hero/videos/'),
        ),
        migrations.AddField(
            model_name='navigation',
            name='logo_image',
            field=models.ImageField(blank=True, help_text='Upload logo image', null=True, upload_to='navigation/'),
        ),
        migrations.AddField(
            model_name='portfolioproject',
            name='media_upload',
            field=models.FileField(blank=True, help_text='Upload project media (image/video)', null=True, upload_to='portfolio/media/'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='image_upload',
            field=models.ImageField(blank=True, help_text='Upload team member photo', null=True, upload_to='team/photos/'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='photo_image',
            field=models.ImageField(blank=True, help_text='Upload customer photo', null=True, upload_to='testimonials/photos/'),
        ),
        migrations.AlterField(
            model_name='hero',
            name='video_url',
            field=models.URLField(blank=True, help_text='OR URL for the hero video', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='navigation',
            name='logo_url',
            field=models.URLField(blank=True, help_text='OR URL for the logo image', max_length=500),
        ),
        migrations.AlterField(
            model_name='portfolioproject',
            name='media_url',
            field=models.URLField(blank=True, help_text='OR Project media URL (image or video)', max_length=500),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='image',
            field=models.URLField(blank=True, help_text='OR Team member photo URL', max_length=500),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='photo',
            field=models.URLField(blank=True, help_text='OR Customer photo URL', max_length=500),
        ),
    ]
