# Generated by Django 5.1.4 on 2025-10-02 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioproject',
            name='service',
            field=models.ForeignKey(blank=True, help_text='Related service for this portfolio project', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portfolio_projects', to='content.serviceitem'),
        ),
    ]
