# Generated by Django 5.1.4 on 2025-10-02 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_portfolioproject_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioproject',
            name='challenge',
            field=models.TextField(blank=True, help_text='The challenge or problem this project solved'),
        ),
        migrations.AddField(
            model_name='portfolioproject',
            name='detailed_description',
            field=models.TextField(blank=True, help_text='Detailed project description for detail page'),
        ),
        migrations.AddField(
            model_name='portfolioproject',
            name='results',
            field=models.TextField(blank=True, help_text='Project results and outcomes'),
        ),
        migrations.AddField(
            model_name='portfolioproject',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-friendly version of title (auto-generated)', max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='portfolioproject',
            name='solution',
            field=models.TextField(blank=True, help_text='How you solved the challenge'),
        ),
    ]
