# Generated by Django 5.1.4 on 2025-10-03 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_portfolioproject_challenge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='hero_video_portrait',
            field=models.FileField(blank=True, help_text='Upload portrait hero video file (Mobile Portrait - 9:16)', null=True, upload_to='hero/videos/'),
        ),
        migrations.AddField(
            model_name='hero',
            name='video_url_portrait',
            field=models.URLField(blank=True, help_text='OR URL for the portrait hero video', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='hero',
            name='hero_video',
            field=models.FileField(blank=True, help_text='Upload hero video file (Landscape/Desktop - 16:9)', null=True, upload_to='hero/videos/'),
        ),
        migrations.AlterField(
            model_name='hero',
            name='video_url',
            field=models.URLField(blank=True, help_text='OR URL for the landscape hero video', max_length=500, null=True),
        ),
    ]
