# Generated by Django 5.1.4 on 2025-10-03 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_hero_hero_video_portrait_hero_video_url_portrait_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='Upload hero image (alternative to video)', null=True, upload_to='hero/images/'),
        ),
        migrations.AddField(
            model_name='hero',
            name='image_url',
            field=models.URLField(blank=True, help_text='OR URL for the hero image', max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='PortfolioGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_upload', models.ImageField(blank=True, help_text='Upload gallery image', null=True, upload_to='portfolio/gallery/')),
                ('image_url', models.URLField(blank=True, help_text='OR Gallery image URL', max_length=500)),
                ('caption', models.CharField(blank=True, help_text='Image caption (optional)', max_length=200)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('portfolio_project', models.ForeignKey(help_text='Related portfolio project', on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='content.portfolioproject')),
            ],
            options={
                'verbose_name': 'Portfolio Gallery Image',
                'verbose_name_plural': 'Portfolio Gallery Images',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
