# Generated by Django 5.1.4 on 2025-10-03 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_hero_hero_image_hero_image_url_portfoliogalleryimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='logo_upload',
            field=models.ImageField(blank=True, help_text='Upload company logo', null=True, upload_to='hero/logos/'),
        ),
        migrations.AddField(
            model_name='hero',
            name='logo_url',
            field=models.URLField(blank=True, help_text='OR URL for the company logo', max_length=500, null=True),
        ),
    ]
