# Generated by Django 5.1.4 on 2025-10-13 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_hero_logo_upload_hero_logo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='hero_image_portrait',
            field=models.ImageField(blank=True, help_text='Upload portrait hero image (Mobile Portrait - 9:16)', null=True, upload_to='hero/images/'),
        ),
        migrations.AddField(
            model_name='hero',
            name='image_url_portrait',
            field=models.URLField(blank=True, help_text='OR URL for the portrait hero image', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='hero',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='Upload hero image (Landscape/Desktop - 16:9)', null=True, upload_to='hero/images/'),
        ),
        migrations.AlterField(
            model_name='hero',
            name='image_url',
            field=models.URLField(blank=True, help_text='OR URL for the landscape hero image', max_length=500, null=True),
        ),
    ]
