# Generated by Django 5.1.4 on 2025-10-13 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_hero_hero_image_portrait_hero_image_url_portrait_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutcontent',
            name='about_image',
            field=models.ImageField(blank=True, help_text='Upload about section image', null=True, upload_to='about/images/'),
        ),
        migrations.AddField(
            model_name='aboutcontent',
            name='about_image_url',
            field=models.URLField(blank=True, help_text='OR URL for the about section image', max_length=500, null=True),
        ),
    ]
